# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='requestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=12)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(default='new', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now_add=True)),
                ('deleted_on', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='requestOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=12)),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.CharField(default='new', max_length=10)),
                ('created_on_by', models.DateTimeField(auto_now_add=True)),
                ('edited_on_by', models.DateTimeField(auto_now_add=True)),
                ('deleted_on_by', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin_on', models.BooleanField(default=False)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='requestitem',
            name='requestOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wfm_client.requestOrder'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
