# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
