# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0003_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_category', models.CharField(max_length=12)),
                ('item_num', models.CharField(max_length=12)),
                ('item_desc', models.CharField(max_length=12)),
                ('item_quantity', models.PositiveIntegerField(default=1)),
                ('item_qcreated_on', models.DateTimeField(auto_now_add=True)),
                ('item_edited_on', models.DateTimeField(auto_now_add=True)),
                ('item_deleted_on', models.DateTimeField(auto_now_add=True)),
                ('item_image', models.ImageField(upload_to='item_image/%Y-%m-%d')),
            ],
        ),
    ]
