# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0004_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_qcreated_on',
            new_name='item_created_on',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='item_number',
        ),
    ]
