# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0006_auto_20160604_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='request_placed',
            field=models.BooleanField(default=False),
        ),
    ]
