# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0007_requestitem_request_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorder',
            name='ordernumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='requestorder',
            name='requestee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
