# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0008_auto_20160607_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorder',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
