# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0009_auto_20160613_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_by_admin_on',
            field=models.BooleanField(default=False),
        ),
    ]
