# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0011_auto_20160615_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='edited_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestorder',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestorder',
            name='edited_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
