# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0012_auto_20160615_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
