# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0015_requestitem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_edited_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
