# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-16 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0017_auto_20160914_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
