# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wfm_client', '0018_auto_20160916_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wfm_client.item')),
                ('requestitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wfm_client.requestItem')),
                ('requestorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wfm_client.requestOrder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
