# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0020_auto_20160917_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='inventory',
        ),
        migrations.AddField(
            model_name='item',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wfm_client.StockHistory'),
        ),
    ]
