# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0021_auto_20160917_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
