# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-18 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0023_auto_20160917_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='message',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
