# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-18 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0025_auto_20160918_0227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockHistory',
            new_name='History',
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'History'},
        ),
    ]
