# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-20 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0028_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='history',
            name='requestitem',
        ),
        migrations.RemoveField(
            model_name='history',
            name='requestorder',
        ),
    ]
