# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0031_requestitem_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='threshold',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
