# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0033_auto_20161031_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='threshold',
        ),
    ]
