# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0034_remove_item_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='threshold',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
