# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-17 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_client', '0035_item_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_quantity_required',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestorder',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
