# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfm_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='department',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
